### ISSUE TITLE
Create trends for moths from RIS data

### ISSUE THREAD

**Issue by AugustT** [AugustT/BRCTracker#2]
Tom is going to work on this, I need to 

- [x] Get data saved locally
- [x] Get the data onto JASMIN
- [x] Update the model to use
- [ ] Get it running on JASMIN
- [ ] Get results off JASMIN
- [ ] Send the results to @NickIssac

**Comment by AugustT** [comment]
@NickIsaac is this the right model? 

[bma_working.zip](https://github.com/AugustT/BRCTracker/files/1471653/bma_working.zip)

**Comment by drnickisaac** [comment]
No - this zip file is from a different project.
