### ISSUE TITLE
Butterfly data for modelling

### ISSUE THREAD

**Issue by AugustT** [AugustT/BRCTracker#4]
I need latest data from @marcBotham

**Comment by marcbotham** [comment]
What is this?

**Comment by AugustT** [comment]
This is me playing around, the issue is not real. I didn't know you were on github! Didn't think the @ would actually reach you, sorry!

**Comment by marcbotham** [comment]
That’s ok, just wondered whether you needed me to do something ☺

**Comment by AugustT** [comment]
This is done now

**Comment by drnickisaac** [comment]
does commenting here reopen the issue?

**Comment by AugustT** [comment]
Nope, you have to click re-open
